//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoRechner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GUIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GUIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoRechner.Properties.GUIStrings", typeof(GUIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Info.
        /// </summary>
        internal static string ButtonAbout {
            get {
                return ResourceManager.GetString("ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marke einfügen.
        /// </summary>
        internal static string ButtonAddBrand {
            get {
                return ResourceManager.GetString("ButtonAddBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teil einfügen.
        /// </summary>
        internal static string ButtonAddPart {
            get {
                return ResourceManager.GetString("ButtonAddPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzer einfügen.
        /// </summary>
        internal static string ButtonAddUser {
            get {
                return ResourceManager.GetString("ButtonAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Zurück zur Übersicht.
        /// </summary>
        internal static string ButtonBackToOverview {
            get {
                return ResourceManager.GetString("ButtonBackToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Abbrechen.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Auto.
        /// </summary>
        internal static string ButtonCar {
            get {
                return ResourceManager.GetString("ButtonCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Leeren.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Datenbank.
        /// </summary>
        internal static string ButtonDatabase {
            get {
                return ResourceManager.GetString("ButtonDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Löschen.
        /// </summary>
        internal static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marke löschen.
        /// </summary>
        internal static string ButtonDeleteBrand {
            get {
                return ResourceManager.GetString("ButtonDeleteBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirklich löschen.
        /// </summary>
        internal static string ButtonDeleteForSure {
            get {
                return ResourceManager.GetString("ButtonDeleteForSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teil löschen.
        /// </summary>
        internal static string ButtonDeletePart {
            get {
                return ResourceManager.GetString("ButtonDeletePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzer löschen.
        /// </summary>
        internal static string ButtonDeleteUser {
            get {
                return ResourceManager.GetString("ButtonDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Bearbeiten.
        /// </summary>
        internal static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Beenden.
        /// </summary>
        internal static string ButtonExit {
            get {
                return ResourceManager.GetString("ButtonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Exportieren.
        /// </summary>
        internal static string ButtonExport {
            get {
                return ResourceManager.GetString("ButtonExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Extra.
        /// </summary>
        internal static string ButtonExtra {
            get {
                return ResourceManager.GetString("ButtonExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hilfe.
        /// </summary>
        internal static string ButtonHelp {
            get {
                return ResourceManager.GetString("ButtonHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Einfügen.
        /// </summary>
        internal static string ButtonInsert {
            get {
                return ResourceManager.GetString("ButtonInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Laden.
        /// </summary>
        internal static string ButtonLoad {
            get {
                return ResourceManager.GetString("ButtonLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Neu.
        /// </summary>
        internal static string ButtonNew {
            get {
                return ResourceManager.GetString("ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Neu berechnen.
        /// </summary>
        internal static string ButtonRecalculate {
            get {
                return ResourceManager.GetString("ButtonRecalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Neu laden.
        /// </summary>
        internal static string ButtonReload {
            get {
                return ResourceManager.GetString("ButtonReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Speichern.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern und beenden.
        /// </summary>
        internal static string ButtonSaveAndClose {
            get {
                return ResourceManager.GetString("ButtonSaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Einstellungen.
        /// </summary>
        internal static string ButtonSettings {
            get {
                return ResourceManager.GetString("ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Statistik.
        /// </summary>
        internal static string ButtonStats {
            get {
                return ResourceManager.GetString("ButtonStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code stimmt nicht überein!.
        /// </summary>
        internal static string CaptchaMismatch {
            get {
                return ResourceManager.GetString("CaptchaMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAS LEEREN DER DATENBANK
        ///FÜHRT ZUM UNWIDERRUFLICHEN
        ///VERLUST ALLER FAHRZEUGE!.
        /// </summary>
        internal static string ClearDatabaseWarning {
            get {
                return ResourceManager.GetString("ClearDatabaseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zusammenfassung.
        /// </summary>
        internal static string Conclusion {
            get {
                return ResourceManager.GetString("Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück zur Fahrzeugübersicht?.
        /// </summary>
        internal static string ConfirmBack {
            get {
                return ResourceManager.GetString("ConfirmBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wirklich beenden?.
        /// </summary>
        internal static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Datei.
        /// </summary>
        internal static string DatabaseExportFilter {
            get {
                return ResourceManager.GetString("DatabaseExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte Chance!!! Wirklich löschen?.
        /// </summary>
        internal static string DropDBLastChance {
            get {
                return ResourceManager.GetString("DropDBLastChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Marke darf nicht leer sein!.
        /// </summary>
        internal static string EmptyBrandError {
            get {
                return ResourceManager.GetString("EmptyBrandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll der Kommentar wirklich leer sein?
        ///Er kann später sehr hilfreich sein!.
        /// </summary>
        internal static string EmptyCommentWarning {
            get {
                return ResourceManager.GetString("EmptyCommentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Modell darf nicht leer sein!.
        /// </summary>
        internal static string EmptyModelError {
            get {
                return ResourceManager.GetString("EmptyModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Teilname darf nicht leer sein!.
        /// </summary>
        internal static string EmptyPartError {
            get {
                return ResourceManager.GetString("EmptyPartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person darf nicht leer sein!.
        /// </summary>
        internal static string EmptyPersonError {
            get {
                return ResourceManager.GetString("EmptyPersonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position darf nicht leer sein!.
        /// </summary>
        internal static string EmptyPositionError {
            get {
                return ResourceManager.GetString("EmptyPositionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername darf nicht leer sein!.
        /// </summary>
        internal static string EmptyUsernameError {
            get {
                return ResourceManager.GetString("EmptyUsernameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Datenbank gefunden!.
        /// </summary>
        internal static string ErrorNoDatabaseFile {
            get {
                return ResourceManager.GetString("ErrorNoDatabaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Einstellungsdatei gefunden!.
        /// </summary>
        internal static string ErrorNoSettingsFile {
            get {
                return ResourceManager.GetString("ErrorNoSettingsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folgender Fehler ist aufgetreten:
        ///
        ///.
        /// </summary>
        internal static string ErrorPrefix {
            get {
                return ResourceManager.GetString("ErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Dies ist normal, wenn das Programm zum allerersten mal auf einem neuen Computer gestartet wird.).
        /// </summary>
        internal static string FirstStart {
            get {
                return ResourceManager.GetString("FirstStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den Eintrag &apos;{0}&apos; wirklich löschen?.
        /// </summary>
        internal static string FormatConfirmDelete {
            get {
                return ResourceManager.GetString("FormatConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Eintrag &apos;{0}&apos; existiert bereits!.
        /// </summary>
        internal static string FormatDuplicateWarning {
            get {
                return ResourceManager.GetString("FormatDuplicateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde kein gültiger Wert für Preis eingetragen!.
        /// </summary>
        internal static string InvalidPriceError {
            get {
                return ResourceManager.GetString("InvalidPriceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Datei.
        /// </summary>
        internal static string InvoiceExportFilter {
            get {
                return ResourceManager.GetString("InvoiceExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer wurde(n) automatisch aus der Datenbank in die Nutzerliste eingefügt..
        /// </summary>
        internal static string LabelAddedUser {
            get {
                return ResourceManager.GetString("LabelAddedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnittliche Kosten.
        /// </summary>
        internal static string LabelAverageCost {
            get {
                return ResourceManager.GetString("LabelAverageCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnittlicher Gewinn.
        /// </summary>
        internal static string LabelAverageProfit {
            get {
                return ResourceManager.GetString("LabelAverageProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durchschnittlicher Verkaufspreis.
        /// </summary>
        internal static string LabelAverageSell {
            get {
                return ResourceManager.GetString("LabelAverageSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marke.
        /// </summary>
        internal static string LabelBrand {
            get {
                return ResourceManager.GetString("LabelBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marken.
        /// </summary>
        internal static string LabelBrands {
            get {
                return ResourceManager.GetString("LabelBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berechnung.
        /// </summary>
        internal static string LabelCalculation {
            get {
                return ResourceManager.GetString("LabelCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha zur Freigabe:.
        /// </summary>
        internal static string LabelCaptcha {
            get {
                return ResourceManager.GetString("LabelCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha eingeben:.
        /// </summary>
        internal static string LabelCaptcha2 {
            get {
                return ResourceManager.GetString("LabelCaptcha2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string LabelCar {
            get {
                return ResourceManager.GetString("LabelCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autos in der Datenbank.
        /// </summary>
        internal static string LabelCarsInDatabase {
            get {
                return ResourceManager.GetString("LabelCarsInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentar.
        /// </summary>
        internal static string LabelComment {
            get {
                return ResourceManager.GetString("LabelComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosten.
        /// </summary>
        internal static string LabelCost {
            get {
                return ResourceManager.GetString("LabelCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standardwert.
        /// </summary>
        internal static string LabelDefaultValue {
            get {
                return ResourceManager.GetString("LabelDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        internal static string LabelDelete {
            get {
                return ResourceManager.GetString("LabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        internal static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahlung.
        /// </summary>
        internal static string LabelDownPayment {
            get {
                return ResourceManager.GetString("LabelDownPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einträge.
        /// </summary>
        internal static string LabelEntry {
            get {
                return ResourceManager.GetString("LabelEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LabelID {
            get {
                return ResourceManager.GetString("LabelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einberechnen.
        /// </summary>
        internal static string LabelInclude {
            get {
                return ResourceManager.GetString("LabelInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechnung.
        /// </summary>
        internal static string LabelInvoice {
            get {
                return ResourceManager.GetString("LabelInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schlüssel.
        /// </summary>
        internal static string LabelKey {
            get {
                return ResourceManager.GetString("LabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprache.
        /// </summary>
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modell.
        /// </summary>
        internal static string LabelModel {
            get {
                return ResourceManager.GetString("LabelModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Teil.
        /// </summary>
        internal static string LabelNewEntry {
            get {
                return ResourceManager.GetString("LabelNewEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        internal static string LabelNo {
            get {
                return ResourceManager.GetString("LabelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht einberechnet.
        /// </summary>
        internal static string LabelNotInclude {
            get {
                return ResourceManager.GetString("LabelNotInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teile.
        /// </summary>
        internal static string LabelParts {
            get {
                return ResourceManager.GetString("LabelParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausschüttung.
        /// </summary>
        internal static string LabelPayout {
            get {
                return ResourceManager.GetString("LabelPayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string LabelPerson {
            get {
                return ResourceManager.GetString("LabelPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string LabelPosition {
            get {
                return ResourceManager.GetString("LabelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preis.
        /// </summary>
        internal static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einnahmen.
        /// </summary>
        internal static string LabelProfit {
            get {
                return ResourceManager.GetString("LabelProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string LabelRestPayment {
            get {
                return ResourceManager.GetString("LabelRestPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string LabelSettings {
            get {
                return ResourceManager.GetString("LabelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summe.
        /// </summary>
        internal static string LabelSum {
            get {
                return ResourceManager.GetString("LabelSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamt.
        /// </summary>
        internal static string LabelTotal {
            get {
                return ResourceManager.GetString("LabelTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtgewinn in.
        /// </summary>
        internal static string LabelTotalProfit {
            get {
                return ResourceManager.GetString("LabelTotalProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        internal static string LabelUsers {
            get {
                return ResourceManager.GetString("LabelUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wert.
        /// </summary>
        internal static string LabelValue {
            get {
                return ResourceManager.GetString("LabelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewinn.
        /// </summary>
        internal static string LabelWin {
            get {
                return ResourceManager.GetString("LabelWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string LabelYes {
            get {
                return ResourceManager.GetString("LabelYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Optionen.
        /// </summary>
        internal static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Anzeige.
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll die Anzahlung wirklich negativ sein?.
        /// </summary>
        internal static string NegativeDownPaymentWarning {
            get {
                return ResourceManager.GetString("NegativeDownPaymentWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll der Preis wirklich negativ sein?.
        /// </summary>
        internal static string NegativePriceWarning {
            get {
                return ResourceManager.GetString("NegativePriceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Auto ausgewählt!.
        /// </summary>
        internal static string NoCarSelected {
            get {
                return ResourceManager.GetString("NoCarSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden noch keine Benutzer angelegt!
        ///Ohne Benutzer ist das Programm nur eingeschränkt nutzbar.
        ///
        ///Jetzt Benutzer anlegen?.
        /// </summary>
        internal static string NoUsersWarning {
            get {
                return ResourceManager.GetString("NoUsersWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausschüttung pro Person.
        /// </summary>
        internal static string PayoutPerPerson {
            get {
                return ResourceManager.GetString("PayoutPerPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgaben pro Person.
        /// </summary>
        internal static string SpendingPerPerson {
            get {
                return ResourceManager.GetString("SpendingPerPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgaben.
        /// </summary>
        internal static string Spendings {
            get {
                return ResourceManager.GetString("Spendings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenbank löschen.
        /// </summary>
        internal static string TitleDeleteDatabase {
            get {
                return ResourceManager.GetString("TitleDeleteDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto bearbeiten.
        /// </summary>
        internal static string TitleEditCar {
            get {
                return ResourceManager.GetString("TitleEditCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eintrag bearbeiten.
        /// </summary>
        internal static string TitleEditEntry {
            get {
                return ResourceManager.GetString("TitleEditEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagramm.
        /// </summary>
        internal static string TitleGraph {
            get {
                return ResourceManager.GetString("TitleGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Auto anlegen.
        /// </summary>
        internal static string TitleNewCar {
            get {
                return ResourceManager.GetString("TitleNewCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistiken.
        /// </summary>
        internal static string TitleStats {
            get {
                return ResourceManager.GetString("TitleStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnung.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
