//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoRechner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoRechner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Auto\par
        ///\b0\fs22 Ein Auto wird \lang1031 Marke und Modell definiert. Verfeinert wird das ganze \&apos;fcber das Kommentarfeld. Zus\&apos;e4tzlich l\&apos;e4sst sich das Kaufdatum notieren.\lang9\par
        ///}.
        /// </summary>
        internal static string helpStrAuto {
            get {
                return ResourceManager.GetString("helpStrAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Datum\par
        ///\b0\fs22 Das Feld &apos;Datum&apos; steht f\&apos;fcr das Kaufdatum und wird zur Berechnung der Statistik verwendet.\par
        ///}.
        /// </summary>
        internal static string helpStrDatum {
            get {
                return ResourceManager.GetString("helpStrDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Einberechnen\par
        ///\b0\fs22 Das Feld \lang2057 &apos;Einberechnen&apos; gibt an, ob der Eintrag in die Kostenrechnung aufgenommen werden soll. Wenn die Option ausgew\lang1031\&apos;e4hlt wird, wird der Preis in die Kosten einsummiert. Wenn die Option nicht ausgew\&apos;e4hlt wird, wird der Preis nicht einsummiert.\par
        ///Durch das Dr\&apos;fccken der T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpStrEinberechnen {
            get {
                return ResourceManager.GetString("helpStrEinberechnen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Eintr\&apos;e4ge\par
        ///\b0\fs22 Jedem Auto wird eine beliebige Anzahl von Eintr\&apos;e4gen zugeordnet. Die Eintr\&apos;e4ge beschreiben Kosten, welche entstanden sind.\par
        ///Beispiele:\par
        ///
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-360\li720\sl240\slmult1 Kaufpreis\par
        ///{\pntext\f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpStrEintraege {
            get {
                return ResourceManager.GetString("helpStrEintraege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Calibri;}{\f1\fnil\fcharset2 Symbol;}}
        ///{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Kommentar\par
        ///\b0\fs22 Das Feld &apos;Kommentar&apos; ist zur eindeutigen Indentifzierung des Autos gedacht. Es ist ein Freitextfeld und kann auch leer gelassen werden.\par
        ///Sinnvolle Ideen zur Verwendung:\par
        ///
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnindent0{\pntxtb\&apos;B7}}\fi-360\li720\sa200\sl240 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpStrKommentar {
            get {
                return ResourceManager.GetString("helpStrKommentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Marke\par
        ///\b0\fs22 Das Feld \lang2057 &apos;Marke&apos; gibt die Automarke an.\fs28\lang9\par
        ///}.
        /// </summary>
        internal static string helpStrMarke {
            get {
                return ResourceManager.GetString("helpStrMarke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Modell\par
        ///\b0\fs22 Das Feld \lang2057 &apos;Modell&apos; gibt das Automodell an.\fs28\lang9\par
        ///}.
        /// </summary>
        internal static string helpStrModell {
            get {
                return ResourceManager.GetString("helpStrModell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Aussch\&apos;fcttung\par
        ///\b0\fs22 Die Aussch\&apos;fcttung ist die Summe, welche jede Person am Ende ausgezahlt bekommt. Die Aussch\&apos;fcttung wird dabei so berechnet, dass jede Person zuerst den eigenen Einsatz ausgezahlt bekommt. Der Gewinn wird dann zu gleichen Anteilen auf alle Personen verteilt.\par
        ///Es wird empfohlen s\&apos;e4mtliche [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpStrPay {
            get {
                return ResourceManager.GetString("helpStrPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Calibri; } }
        ///                {\*\generator Riched20 10.0.19041}\viewkind4\uc1
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Person\par
        ///\b0\fs22 Das Feld &apos;Person&apos; beschreibt, welche Person diese Position bezahlt hat.\line Personen k\lang1031\&apos;f6nnen in den Einstellungen hinzugef\&apos;fcgt werden.\par
        ///Die Person \lang2057 &apos;Offen&apos; ist ein Spezialfall und repr\lang1031\&apos;e4sentiert, dass die Position (noch) von Niemandem bezahlt wurde.\ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpStrPerson {
            get {
                return ResourceManager.GetString("helpStrPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Riched20 10.0.19041}\viewkind4\uc1 
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Position\par
        ///\b0\fs22 Das Feld &apos;Position&apos; beschreibt den Eintrag.Dies kann der Name eines Ersatzteils, einer Dienstleistung oder auch Teilenummer sein.\fs28\par
        ///}.
        /// </summary>
        internal static string helpStrPosition {
            get {
                return ResourceManager.GetString("helpStrPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang2057{\fonttbl{\f0\fnil\fcharset0 Calibri;
        ///                    }
        ///                    {\f1\fnil\fcharset2 Symbol;
        ///                    }
        ///                }
        ///                {\*\generator Riched20 10.0.19041}\viewkind4\uc1
        ///\pard\sa200\sl276\slmult1\b\f0\fs28\lang9 Preis\par
        ///\b0\fs22 Das Feld &apos;Preis&apos; beschreibt den Preis des Eintrags.Der Preis wird dabei als Kommazahl eingegeben. \par
        ///\par
        ///Beispiele:\par
        ///
        ///\pard{\pntext\f1\&apos;B7\tab}{\*\pn\pnlvlblt\pnf1\pnind [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpStrPreis {
            get {
                return ResourceManager.GetString("helpStrPreis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offen.
        /// </summary>
        internal static string UserNone {
            get {
                return ResourceManager.GetString("UserNone", resourceCulture);
            }
        }
    }
}
